
spring:
  datasource:
    url: jdbc:h2:mem:restaurant

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  http:
    client:
      read-timeout: 3000
      connect-timeout: 3000
  profiles:
    active: secret

springdoc:
  swagger-ui:
    path: /api-docs

server:
  forward-headers-strategy: native
